name: reusable-dotnet-publish

on:
  workflow_call:
    inputs:
      runner:
        type: string
        default: ubuntu-latest
      dotnet_version:
        type: string
        default: 8.0.x
      configuration:
        type: string
        default: Release
      publish_output:
        type: string
        default: ./publish
      artifact_name:
        type: string
        default: dotnet-publish-output

jobs:
  publish:
    name: Publish
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet_version }}

      - name: Publish
        run: dotnet publish --configuration ${{ inputs.configuration }} --output ${{ inputs.publish_output }} --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ inputs.publish_output }}
